### ISSUE TITLE
Deletection of ThirdParty libraries is broken with gcc 5.4.0

### ISSUE THREAD

**Issue by tkralphs** [coin-or-tools/BuildTools#1]
It seems that with gcc 5.4.0 (or maybe earlier), implicit function declaration went from being a warning to being an error and there doesn't seem to be any way to change this behavior. Our tests for whether a library exists don't properly add the include paths to the flags, so there is always an implicit function declaration for the function we are looking in the library for and this causes compilation of the test program that is trying to link to the library (and hence detection of the library) to fail. I guess it should be an easy fix.

**Comment by svigerske** [comment]
Could it be an error because of the extra warning flags we send to gcc? It has been suggested for some projects, that one should disable the compiler warning flags (e.g., set coin_skip_warn_cxx) to get configure passing. So an easy fix might be to disable them globally.

**Comment by svigerske** [comment]
I tried out Osi with Gurobi with gcc 6.2.1. I can reproduce your failure:

> configure:23874: gcc -o conftest -g -O0 -pipe -pedantic-errors -Wimplicit -Wparentheses -Wsequence-point -Wreturn-type -Wcast-qual -Wall -Wno-unknown-pragma
> conftest.c: In function 'main':
> conftest.c:39:1: error: implicit declaration of function 'GRBloadenv' [-Wimplicit-function-declaration]
>  GRBloadenv()
>  ^~~~~~~~~~

But when I add coin_skip_warn_cflags=yes as arugment to configure, then it runs through:

> checking if user provides library for Gurobi... yes
> checking whether symbol GRBloadenv is available with GRB... yes

Now, in config.log, it's just a warning:

> configure:23874: gcc -o conftest -g -O0 -pipe    -DOSI_BUILD   conftest.c -L/home/stefan/work/gams/products/platform/libleg/ -lgurobi -lpthread -lm  >&5
> conftest.c: In function 'main':
> conftest.c:40:1: warning: implicit declaration of function 'GRBloadenv' [-Wimplicit-function-declaration]
>  GRBloadenv()
>  ^~~~~~~~~~

I would think this is from ommitting `-pedantic-errors`. I'll try this out and if that do it, then I think we should just omit this from the flags.

**Comment by svigerske** [comment]
This should be taken care of in BuildTools/stable/0.8 now. Reopen if you think otherwise.
