### ISSUE TITLE
Prefix doesn't necessarily exist

### ISSUE THREAD

**Issue by tkralphs** [coin-or-tools/BuildTools#127]
There is the following line in `coin.m4` [here](https://github.com/coin-or-tools/BuildTools/blob/stable/0.8/coin.m4#L1463):
```
full_prefix=`cd $full_prefix ; pwd`
```
This assumes the prefix exists, which it need not. I don't actually see the purpose of this, since the prefix must be specified as a full path anyway. If the prefix doesn't exist, this just spits out an error and doesn't cause the configure to fail, but it would be nice if this didn't happen.

**Comment by svigerske** [comment]
I'll just believe you on the "must be specified as a full path" and so removed this line.
Thanks.

**Comment by tkralphs** [comment]
I don't know why/where the requirement is enforced, but here you go:

~/Projects/CoinUtils > mkdir build
~/Projects/CoinUtils > cd build; ../configure --prefix=test
configure: error: expected an absolute directory name for --prefix: test
