### ISSUE TITLE
Allow source in subdirectories

### ISSUE THREAD

**Issue by tkralphs** [coin-or-tools/BuildTools#133]
Is there a reason not to allow source to be in subdirectories? I'm in the process of converting SYMPHONY to the new build system. Currently, SYMPHONY has a multi-level structure in its `src` directory and this is not supported in `master`. Changing the call to `AM_INIT_AUTOMAKE` to 
```
AM_INIT_AUTOMAKE([no-define no-dist -Wall subdir-objects])
```
fixes the issue. Is there any downside to this?

**Comment by svigerske** [comment]
I usually put the subdir-objects into the Makefile.am where necessary:
```
AUTOMAKE_OPTIONS = foreign subdir-objects
```

**Comment by tkralphs** [comment]
Ah, OK, I missed that you can do that. Thanks!

**Comment by svigerske** [comment]
I'll still give it a try to add this to AM_INIT_AUTOMAKE.

**Comment by svigerske** [comment]
@tkralphs You can (and probably should) leave out the setting of `AUTOMAKE_OPTIONS` in Makefile.am. The current `AUTOMAKE_OPTIONS = foreign` seems to have overwritten AM_INIT_AUTOMAKE setting from coin.m4. At least the `-Wall` didn't seem to have been applied.
