### ISSUE TITLE
Issue with conditional in lib_LTLIBRARIES

### ISSUE THREAD

**Issue by tkralphs** [coin-or-tools/BuildTools#135]
I've been struggling to figure out a problem I'm having building SYMPHONY when the set of libraries to build is figured out at compile time. In a nutshell, some libraries are only built when the build is parallel. So I set 
```
lib_LTLIBRARIES = $(WHATTOINSTALLLIBS)
```
where `WHATTOINSTALLLIBS` is set in `configure`. Because some libraries are defined, but not built/installed, we have defined `EXTRA_LDLIBRARIES`, which includes all possible libraries---those to be built and those not to be built. This has always worked fine.

With the new build tools version, as long as I only build the core SYMPHONY library and don't use a conditional in `lib_LTLIBRARIES` (and thus also don't use `EXTRA_LTLIBRARIES`), everything is fine, but as soon as I introduce the conditional, then the rule for `libSym` changes subtly for some reason and the library is built statically. I eventually get the error
```
libtool: install: /usr/bin/install -c .libs/libSym.lai /mnt/c/Users/tkral/Documents/Projects/dist/lib/libSym.la
/usr/bin/install: cannot stat '.libs/libSym.lai': No such file or directory
```
which seems to happen when a shared library is expected, but a static one is built. The change to building a static library instead of a shared one seems to be triggered purely as a result of the deletion of `-rpath` from the build target. This is the diff between a working version and a non-working one and that's the only difference:
https://github.com/coin-or/SYMPHONY/commit/c21761f5f90eb37b80c98ef187c0729213b46db5#diff-78b87d56b04973fda4242a02f90dce32
I also verified that this difference is the only one in the actual `Makefile`s produced.

At this point, I can't see where this change is coming from. I could probably dig even deeper, but I've been on this for a week and finally narrowed it down to this. I thought it was a good time to see if any of the experts had any ideas.

**Comment by svigerske** [comment]
~~My guess is that specifying libs in `EXTRA_LTLIBRARIES` declares them to be a [libtool convenience library](https://www.gnu.org/software/automake/manual/html_node/Libtool-Convenience-Libraries.html) and these are always build statically (as `.a`, but compiled with `-fPIC`), since they are not installed and just used to make up a larger library (which is then a shared one by default).~~
~~If you add a library to both `lib_LTLIBRARIES` and `EXTRA_LTLIBRARIES`, then automake may get confused.~~

[This documentation](https://www.gnu.org/software/automake/manual/html_node/Conditional-Libtool-Libraries.html#Conditional-Libtool-Libraries) says that if you use `EXTRA_LTLIBRARIES`, then you need to add the `-rpath` explicitly.

**Comment by tkralphs** [comment]
OK, thanks for tracking that down @svigerske! I did look at documentation, but didn't find that detail. I can't make sense out of the difference between the two implementations they provide there, though. In both cases, all the details for the libraries _are_ explicitly knows. It _is_ clear **where** the libraries will be installed in both case, just not **if** they will be installed. I simply don't see why `-rpath` can't be added automatically in both cases. But ah well, I'm sure there's a reason.

Another thing I don't understand is why leaving out `-rpath` results in static libraries. You can't build a shared library without `-rpath`? Is this really "the way" you tell libtool whether you are building shared or static libraries?  If it knows it is building a static library, why does it look for the `.lai` file and fail to install in the first place? The whole thing doesn't seem to make sense to me.

But anyway, after overcoming a few more challenges that were a weird combination of things going wrong, I finally got the libraries building conditionally now. Thanks!

**Comment by svigerske** [comment]
While automake is running, it wouldn't know where the libs you mention in `EXTRA_LTLIBRARIES` are going to be installed (if being installed at all). It can't really know in which libxyz_LTLIBRARIES variables the libs will show up and it seems that it doesn't seem possible to figure this out while make is running.
