### ISSUE TITLE
In stable/0.8, --with-xyz-lib doesn't actually do the link check if Xyz is a COIN-OR project 

### ISSUE THREAD

**Issue by tkralphs** [coin-or-tools/BuildTools#142]
This report applies to stable/0.8 and uses BLAS as a case-in-point, but it appears the same bug applies to specifying pre-built libraries for any other COIN-OR project using --with-xxx-lib. 

In stable/0.8, there are two different ways of specifying BLAS libraries, --with-blas="$LIB_FLAGS" and --with-blas-lib="$LIB_FLAGS". It's not really clear to me how this came to be, but `--with-blas` treats BLAS as a user-supplied library, while `--with-blas-lib` treats BLAS as a COIN-OR project. The latter is buggy (or it has an undocumented "feature"). If one passes flags with --with-blas-lib, `AC_COIN_CHECK_PACKAGE_BLAS` punts to `AC_COIN_CHECK_PACKAGE`, and in that macro, no checks are done at all, it just stores the flags and reports that the COIN-OR package is present. There are actually two errors there. 

- It is reporting that the ThirdParty package is present when it actually isn't and wasn't even checked for. 
- It is not checking the user-supplied flags for validity. 

If you check out CoinUtils stable/2.11 on its own (without ThirdParty BLAS) and do
```
../configure --with-blas-lib="-L/usr/foo -lbar"
```
it will still happily report
```
checking for COIN-OR package Blas... yes
```
even though Blas is nowhere to be found. The same is true if you check out Osi stable/0.108 and specify the location of CoinUtils libraries with `--with-coinutils-lib`. If you do
```
../configure --with-coinutils-lib="-L/usr/foo -lbar"
```
it will happily report
```
checking for COIN-OR package CoinUtils... yes
```
and then the build fails immediately when it can't find the header files. I'm not sure how this has managed to remain undetected for so long. Those flags are not much used, but I would have thought someone would stumble on this. It's coming up now because it caused a failure in the builds for conda packages.

**Comment by svigerske** [comment]
That there is no link-check for packages is known and seems to be expected. By default, we check whether we can get flags from pkg-config and don't verify that they work, either. The `--with-xyz-{lib,incdir}` is an alternative to achieve the same without pkg-config, so also no check that something can actually be linked or headers are found. The `AC_COIN_CHECK_PACKAGE` macro doesn't even get a function name or header file name to check for.

The `--with-blas-{lib,incdir}` are there because there is a COIN-OR package ThirdParty/Blas that it is looking for. If you specify `--with-blas-lib`, it is continuing like for other packages and assumes that the flags are ok. But the build seems to fail then.   
I am unsure that it's worth to touch stable/0.8 just to make it an error from configure already (who knows what I would break).   
On master, `---with-lapack` and `--with-lapack-lflags` are handled equivalently, configure does a link-check, and gives an error if they doesn't work.

**Comment by tkralphs** [comment]
I eventually figured that this is how it evolved, but it's pretty confusing and I would definitely want to change it somehow if it weren't that stable/0.8 will be discontinued soon. It makes sense to me that we don't do a check with a .pc file, since we would have a high degree of trust in those, but it doesn't make sense to me that we don't do a link check with user-supplied link flags, as those should not be trusted. In any case, we _do_ perform a link check when the flags are specified with `--with-blas` (see [here](https://github.com/coin-or-tools/BuildTools/blob/stable/0.8/coin.m4#L3902)). The configuration _will fail_ if the link flags are incorrect with `--with-blas`. I don't see why we trust user flags in one case and not in the other.  

What would simplify things and make it more transparent would be to go the other way---treat all flags specified with --with-Xxx-lib the same way, whether they are COIN-OR projects or not, i.e., don't trust any user-supplied flags. I guess this would be pretty easy to implement, but I understand if you don't want to touch this old build system anymore. If anyone else had been reporting issues with it, I would say let's fix it, since I'm sure people will be using Cbc 2.10 for some time, but given that this doesn't seem to be coming up, I guess we can leave it.

**Comment by svigerske** [comment]
I agree that the treatment of `--with-blas` vs `--with-blas-lib` is inconsistent and from a user's point of view, it's not clear why that would be the case (or why there would be two configure options to do the same thing at the first place). If that would be a blocker for something or be on master, I agree that this should be fixed.

I don't find it too wrong to trust the user-supplied link flags in general. Someone could argue that if a user took the effort and explicitly passed on parameter to configure, who are we (=the build system) to doubt them. Sometimes the build may even still succeed. That doesn't mean that I want to disable all the checks now. :)

**Comment by tkralphs** [comment]
I guess the use case that would justify it is exactly the case where this came up. The "user-supplied" flags may actually be auto-generated as part of some larger build system (conda in this case), so it may not be the case that someone took some care in determining the exact link flags. There could be bugs in the way the link flags are being generated. You could say this is not really our problem, but the lack of link check does make it very difficult to see what's going on.
