### ISSUE TITLE
Audit DocFiles

### ISSUE THREAD

**Issue by xmunoz** [coin-or-tools/BuildTools#149]
Ref: https://github.com/coin-or/CoinUtils/pull/161#issuecomment-830424549

Check to see what text files are present in the projects hosted in the COIN-OR organization, and clean up [DocFiles](https://github.com/coin-or-tools/BuildTools/blob/ea783d8479edc393559f89587fc86e26beed6d83/Makemain.inc#L38) such that it's a representative list.

**Comment by svigerske** [comment]
I don't know what the problem with the current list is. Is there a reason this needs to be shorter? As far as I see, the install-doc target just copies any of those files from the list that it finds.
Does something needs to be added there?

**Comment by xmunoz** [comment]
@tkralphs and I discussed removing the `AUTHORS` file from the repositories, it hasn't been updated in over a decade, and the README's now include links to Github, which is where one can find the authoritative list of authors.

There are other un-used files in there as well. From what I can tell, all repositories contain `README.md`, and not `README`. So this issue is to just audit all of the text files that are in use, and eliminate the ones that aren't from that list.

**Comment by svigerske** [comment]
I saw a README in OS. I have AUTHORS in Ipopt and it is maintained.

**Comment by xmunoz** [comment]
Do you know of any repositories where `LICENSE.md` is in use?

**Comment by svigerske** [comment]
No, I think this was just added to make it all look symmetric. :)

**Comment by tkralphs** [comment]
For now, there are still many projects with READMEs. As we work through all projects and adapt them to the new workflows (much remains to be done), all READMEs will be converted to README.md, but it will actually be quite some time for that to happen. I guess that for now, LICENSE is still the standard name for that type of file, although I guess we could move to LICENSE.md is that doesn't disrupt anything in terms of packaging.

**Comment by xmunoz** [comment]
Alright, here is my proposal for what this line should look like:

```
DocFiles =  README README.md AUTHORS LICENSE
```

Markdown licenses aren't really a thing AFAIK, and more discussion is required before the decision is made to remove `AUTHORS`: https://github.com/coin-or/Cbc/issues/394
