### ISSUE TITLE
Links broken in documentation

### ISSUE THREAD

**Issue by tkralphs** [coin-or-tools/BuildTools#152]
I don't know if it matters at all, but the internal links in the Documentation for version stable/0.8 are all broken because they are missing the `.md` suffix. For example, see the very first link [here](https://github.com/coin-or-tools/BuildTools/blob/stable/0.8/docs/pm-autotools-intro.md).

**Comment by svigerske** [comment]
If one wants the links to work on the GitHub Pages visualization, then I think one needs to omit the `.md`. At least the docu for master is working that way: https://coin-or-tools.github.io/BuildTools/  https://raw.githubusercontent.com/coin-or-tools/BuildTools/master/docs/index.md

But for 0.8 or even earlier, we don't use GitHub pages. Will need to see whether it will be easy to add all missing `.md`.

**Comment by svigerske** [comment]
Added the .md extension.

There is more broken in these files, but, yeah, I don't think they still matter.
