### ISSUE TITLE
--git is not obeyed for Data dependencies in get.dependencies.sh

### ISSUE THREAD

**Issue by juan-pablo-vielma** [coin-or-tools/BuildTools#3]
https://github.com/coin-or-tools/BuildTools/blob/f061d4713c0d3e2377d51f610a9911a635a16bd2/get.dependencies.sh#L350-L354

**Comment by tkralphs** [comment]
This is because the Data dependencies are not currently mirrored to git. I hope to change that soon.

**Comment by svigerske** [comment]
@tkralphs  changed this recently in his work on https://github.com/coin-or/COIN-OR-OptimizationSuite/blob/master/coin.install.sh

**Comment by svigerske** [comment]
More on this, if necessary, on the official BuildTools issue tracker: https://projects.coin-or.org/BuildTools/ticket/120#no4
